"""
ACORD 126 (Commercial General Liability) field mappings.

Usage:
    from acord_field_mappings import get_field_mapping, get_supported_forms

    fmap = get_field_mapping('126')
"""

from typing import Dict

# Matches actual field names from ACORD_126.pdf you extracted.
ACORD_126_FIELD_MAP: Dict[str, str] = {
            # Existing mappings
            "applicant.business_name": "NamedInsured_FullName_A",
            "coverage_type.occurrence": "GeneralLiability_OccurrenceIndicator_A",
            "limits.each_occurrence": "GeneralLiability_EachOccurrence_LimitAmount_A",
            "limits.general_aggregate": "GeneralLiability_GeneralAggregate_LimitAmount_A",
            "limits.products_completed_ops": "GeneralLiability_ProductsAndCompletedOperations_AggregateLimitAmount_A",
            "limits.personal_adv_injury": "GeneralLiability_PersonalAndAdvertisingInjury_LimitAmount_A",
            "limits.medical_expense": "GeneralLiability_MedicalExpense_EachPersonLimitAmount_A",
            "limits.fire_damage": "GeneralLiability_FireDamageRentedPremises_EachOccurrenceLimitAmount_A",
            "operations.hazards_description": "GeneralLiabilityLineOfBusiness_RemarkText_A",
            "operations.subcontractors_used": "GeneralLiabilityLineOfBusiness_RemarkText_A",
            "operations.products_sold": "GeneralLiabilityLineOfBusiness_RemarkText_B",
            "additional_insureds[0].name": "AdditionalInterest_FullName_A",
            # New mappings
            "applicant.signature": "NamedInsured_Signature_A",
            "applicant.signature_date": "NamedInsured_SignatureDate_A",
            "coverage_type.claims_made": "GeneralLiability_ClaimsMadeIndicator_A",
            "claims_made.retro_date": "GeneralLiability_ClaimsMade_ProposedRetroactiveDate_A",
            "claims_made.uninterrupted_coverage_entry_date": "GeneralLiability_ClaimsMade_UninterruptedCoverageEntryDate_A",
            "limits.employee_benefits": "GeneralLiability_EmployeeBenefits_LimitAmount_A",
            "limits.other_coverage_limit": "GeneralLiability_OtherCoverageLimitAmount_A",
            "deductibles.property_damage": "GeneralLiability_PropertyDamage_DeductibleAmount_A",
            "deductibles.bodily_injury": "GeneralLiability_BodilyInjury_DeductibleAmount_A",
            "deductibles.other": "GeneralLiability_OtherDeductibleAmount_A",
            "deductibles.per_claim": "GeneralLiability_DeductiblePerClaimIndicator_A",
            "deductibles.per_occurrence": "GeneralLiability_DeductiblePerOccurrenceIndicator_A",
            "premiums.premises_operations": "GeneralLiability_PremisesOperations_PremiumAmount_A",
            "premiums.products": "GeneralLiability_Products_PremiumAmount_A",
            "premiums.other_coverage": "GeneralLiability_OtherCoveragePremiumAmount_A",
            "premiums.total": "GeneralLiabilityLineOfBusiness_TotalPremiumAmount_A",
            "producer.full_name": "Producer_FullName_A",
            "producer.state_license": "Producer_StateLicenseIdentifier_A",
            "producer.national_identifier": "Producer_NationalIdentifier_A",
            "producer.authorized_representative_signature": "Producer_AuthorizedRepresentative_Signature_A",
            "producer.customer_identifier": "Producer_CustomerIdentifier_A",
            "policy.policy_number": "Policy_PolicyNumberIdentifier_A",
            "policy.effective_date": "Policy_EffectiveDate_A",
            "policy.completion_date": "Form_CompletionDate_A",
            "insurer.full_name": "Insurer_FullName_A",
            "insurer.naic_code": "Insurer_NAICCode_A",
            "operations.class_code": "GeneralLiability_Hazard_ClassCode_A",
            "operations.premium_basis_code": "GeneralLiability_Hazard_PremiumBasisCode_A",
            "operations.exposure": "GeneralLiability_Hazard_Exposure_A",
            "operations.territory_code": "GeneralLiability_Hazard_TerritoryCode_A",
            "operations.premises_operations_rate": "GeneralLiability_Hazard_PremisesOperationsRate_A",
            "operations.products_rate": "GeneralLiability_Hazard_ProductsRate_A",
            "operations.classification": "GeneralLiability_Hazard_Classification_A",
            "operations.additional_hazard.location_producer_id": "GeneralLiability_Hazard_LocationProducerIdentifier_B",
            "operations.additional_hazard.hazard_producer_id": "GeneralLiability_Hazard_HazardProducerIdentifier_B",
            "operations.additional_hazard.class_code": "GeneralLiability_Hazard_ClassCode_B",
            "operations.additional_hazard.premium_basis_code": "GeneralLiability_Hazard_PremiumBasisCode_B",
            "operations.additional_hazard.exposure": "GeneralLiability_Hazard_Exposure_B",
            "operations.additional_hazard.territory_code": "GeneralLiability_Hazard_TerritoryCode_B",
            "operations.additional_hazard.premises_operations_rate": "GeneralLiability_Hazard_PremisesOperationsRate_B",
            "operations.additional_hazard.products_rate": "GeneralLiability_Hazard_ProductsRate_B",
            "operations.additional_hazard.classification": "GeneralLiability_Hazard_Classification_B",
            "questions.aa_a_code": "GeneralLiabilityLineOfBusiness_Question_AAICode_A",
            "questions.aa_b_code": "Contractors_Question_AABCode_A",
            "questions.aa_c_code": "Contractors_Question_AACCode_A",
            "questions.aa_d_code": "Contractors_Question_AADCode_A",
            "questions.aa_e_code": "Contractors_Question_AAECode_A",
            "questions.aa_f_code": "GeneralLiabilityLineOfBusiness_Question_AAFCode_A",
            "questions.aa_g_code": "Contractors_Question_AAGCode_A",
            "questions.aa_h_code": "Contractors_Question_AAHCode_A",
            "questions.aa_i_code": "GeneralLiabilityLineOfBusiness_Question_AAICode_A",
            "questions.aa_j_code": "GeneralLiabilityLineOfBusiness_Question_AAJCode_A",
            "questions.ab_a_code": "GeneralLiabilityLineOfBusiness_Question_ABACode_A",
            "questions.ab_b_code": "GeneralLiabilityLineOfBusiness_Question_ABBCode_A",
            "questions.ab_c_code": "GeneralLiabilityLineOfBusiness_Question_ABCCode_A",
            "questions.ab_d_code": "GeneralLiabilityLineOfBusiness_Question_ABDCode_A",
            "questions.ab_e_code": "GeneralLiabilityLineOfBusiness_Question_ABECode_A",
            "questions.ab_f_code": "GeneralLiabilityLineOfBusiness_Question_ABFCode_A",
            "questions.ab_g_code": "GeneralLiabilityLineOfBusiness_Question_ABGCode_A",
            "questions.ab_h_code": "GeneralLiabilityLineOfBusiness_Question_ABHCode_A",
            "questions.ab_i_code": "GeneralLiabilityLineOfBusiness_Question_ABICode_A",
            "questions.ac_a_code": "GeneralLiabilityLineOfBusiness_Question_ACACode_A",
            "questions.ac_b_code": "GeneralLiabilityLineOfBusiness_Question_ACBCode_A",
            "questions.ac_c_code": "GeneralLiabilityLineOfBusiness_Question_ACCCode_A",
            "questions.ac_d_code": "GeneralLiabilityLineOfBusiness_Question_ACDCode_A",
            "questions.ac_e_code": "GeneralLiabilityLineOfBusiness_Question_ACECode_A",
            "questions.ac_f_code": "GeneralLiabilityLineOfBusiness_Question_ACFCode_A",
            "questions.ac_g_code": "GeneralLiabilityLineOfBusiness_Question_ACGCode_A",
            "questions.ac_h_code": "GeneralLiabilityLineOfBusiness_Question_ACHCode_A",
            "questions.ac_j_code": "GeneralLiabilityLineOfBusiness_Question_ACJCode_A",
            "questions.ka_a_code": "GeneralLiabilityLineOfBusiness_Question_KAACode_A",
            "questions.ka_g_code": "GeneralLiabilityLineOfBusiness_Question_KAGCode_A",
            "questions.ka_h_code": "GeneralLiabilityLineOfBusiness_Question_KAHCode_A",
            "questions.kab_code": "GeneralLiabilityLineOfBusiness_Question_KABCode_A",
            "explanations.applicant_draw_plans": "GeneralLiabilityLineOfBusiness_ApplicantDrawPlansForOthersExplanation_A",
            "explanations.blasting_operations": "GeneralLiabilityLineOfBusiness_OperationsIncludeBlastingExplanation_A",
            "explanations.evacuation_operations": "GeneralLiabilityLineOfBusiness_OperationsIncludeEvacuationExplanation_A",
            "explanations.subcontractors_lower_limits": "GeneralLiabilityLineOfBusiness_SubcontractorsCarryLowerLimitsExplanation_A",
            "explanations.subcontractors_no_coi": "GeneralLiabilityLineOfBusiness_SubcontractorsWorksWithoutCertificatesOfInsuranceExplanation_A",
            "explanations.equipment_leased": "GeneralLiabilityLineOfBusiness_ApplicantLeaseEquipmentToOthersExplanation_A",
            "explanations.install_service_products": "GeneralLiabilityLineOfBusiness_ApplicantInstallServiceProductsExplanation_A",
            "explanations.research_development": "GeneralLiabilityLineOfBusiness_ResearchDevelopmentConductedNewProductsPlannedExplanation_A",
            "explanations.guarantees_warranties": "GeneralLiabilityLineOfBusiness_GuaranteesWarrantiesHoldHarmlessExplanation_A",
            "explanations.aircraft_industry": "GeneralLiabilityLineOfBusiness_ProductsRelatedToAircraftIndustryExplanation_A",
            "explanations.products_recalled": "GeneralLiabilityLineOfBusiness_ProductsRecalledDiscontinuedExplanation_A",
            "explanations.products_others_label": "GeneralLiabilityLineOfBusiness_ProductsOfOthersSoldUnderApplicantLabelExplanation_A",
            "explanations.products_under_others": "GeneralLiabilityLineOfBusiness_ProductsUnderLabelOfOthersExplanation_A",
            "explanations.vendor_coverage": "GeneralLiabilityLineOfBusiness_VendorCoverageRequiredExplanation_A",
            "explanations.named_insured_sell": "GeneralLiabilityLineOfBusiness_NamedInsuredSellToOtherNamedInsuredExplanation_R",
            "explanations.medical_facilities": "GeneralLiabilityLineOfBusiness_AnyMedicalFacilitiesProvidedMedicalProfessionalsEmployedExplanation_A",
            "explanations.radioactive_materials": "GeneralLiabilityLineOfBusiness_AnyExposureRadioactiveMaterialsExplanation_A",
            "explanations.hazardous_materials": "GeneralLiabilityLineOfBusiness_OperationsInvolveStoringDisposingTransportingHazardousMaterialExplanation_A",
            "explanations.operations_sold_acquired": "GeneralLiabilityLineOfBusiness_AnyListedOperationsSoldAcquiredLastFiveYearsExplanation_A",
            "explanations.equipment_loaned_rented": "GeneralLiabilityLineOfBusiness_MachineryOrEquipmentLoanedRentedOthersExplanation_A",
            "explanations.watercraft_docks": "GeneralLiabilityLineOfBusiness_WatercraftDocksFloatsOwnedHiredLeasedExplanation_A",
            "explanations.parking_facilities": "GeneralLiabilityLineOfBusiness_AnyParkingFacilitiesOwnedRentedExplanation_A",
            "explanations.fee_for_parking": "GeneralLiabilityLineOfBusiness_FeeChargedForParkingExplanation_A",
            "explanations.recreational_facilities": "GeneralLiabilityLineOfBusiness_RecreationalFacilitiesProvidedExplanation_A",
            "explanations.sporting_events": "GeneralLiabilityLineOfBusiness_SportingOrSocialEventsSponsoredExplanation_A",
            "explanations.structural_alterations": "GeneralLiabilityLineOfBusiness_StructuralAlterationsContemplatedExplanation_A",
            "explanations.demolition_exposure": "GeneralLiabilityLineOfBusiness_DemolitionExposureContemplatedExplanation_A",
            "explanations.joint_ventures": "GeneralLiabilityLineOfBusiness_ApplicantActiveJointVenturesExplanation_A",
            "explanations.labor_interchange": "GeneralLiabilityLineOfBusiness_LabourInterchangeOtherBusinessSubsidiariesExplanation_A",
            "explanations.day_care_facilities": "GeneralLiabilityLineOfBusiness_DayCareFacilitiesOperatedExplanation_A",
            "explanations.crimes_last_three_years": "GeneralLiabilityLineOfBusiness_CrimesOccurredOrAttemptedLastThreeYearsExplanation_A",
            "explanations.safety_policy": "GeneralLiabilityLineOfBusiness_FormalSafetySecurityPolicyInEffectExplanation_A",
            "explanations.promotional_literature": "GeneralLiabilityLineOfBusiness_BusinessPromotionalLiteratureSafetyRepresentationsExplanation_A",
            "contractors.subcontractors_paid": "Contractors_SubcontractorsPaidAmount_A",
            "contractors.work_subcontracted_percent": "Contractors_WorkSubcontractedPercent_A",
            "contractors.full_time_employees": "Contractors_FullTimeEmployeeCount_A",
            "contractors.part_time_employees": "Contractors_PartTimeEmployeeCount_A",
            "contractors.type_of_work_subcontracted": "GeneralLiabilityLineOfBusiness_TypeOfWorkSubcontractedDescription_A",
            "products_and_completed_operations.product_a.name": "ProductAndCompletedOperations_ProductName_A",
            "products_and_completed_operations.product_a.annual_gross_sales": "ProductAndCompletedOperations_AnnualGrossSalesAmount_A",
            "products_and_completed_operations.product_a.unit_count": "ProductAndCompletedOperations_UnitCount_A",
            "products_and_completed_operations.product_a.in_market_months": "ProductAndCompletedOperations_InMarketMonthCount_A",
            "products_and_completed_operations.product_a.expected_life_months": "ProductAndCompletedOperations_ExpectedLifeMonthCount_A",
            "products_and_completed_operations.product_a.intended_use": "ProductAndCompletedOperations_IntendedUse_A",
            "products_and_completed_operations.product_a.principal_components": "ProductAndCompletedOperations_PrincipalComponents_A",
            "products_and_completed_operations.product_b.name": "ProductAndCompletedOperations_ProductName_B",
            "products_and_completed_operations.product_b.annual_gross_sales": "ProductAndCompletedOperations_AnnualGrossSalesAmount_B",
            "products_and_completed_operations.product_b.unit_count": "ProductAndCompletedOperations_UnitCount_B",
            "products_and_completed_operations.product_b.in_market_months": "ProductAndCompletedOperations_InMarketMonthCount_B",
            "products_and_completed_operations.product_b.expected_life_months": "ProductAndCompletedOperations_ExpectedLifeMonthCount_B",
            "products_and_completed_operations.product_b.intended_use": "ProductAndCompletedOperations_IntendedUse_B",
            "products_and_completed_operations.product_b.principal_components": "ProductAndCompletedOperations_PrincipalComponents_B",
            "athletic_team.team_a.sport_description": "AthleticTeam_SportDescription_A",
            "athletic_team.team_a.contact_sport": "AthleticTeam_ContactSportCode_A",
            "athletic_team.team_a.age_group_twelve_and_under": "AthleticTeam_AgeGroup_TwelveAndUnderIndicator_A",
            "athletic_team.team_a.age_group_thirteen_through_eighteen": "AthleticTeam_AgeGroup_ThirteenThroughEighteenIndicator_A",
            "athletic_team.team_a.age_group_over_eighteen": "AthleticTeam_AgeGroup_OverEighteenIndicator_A",
            "athletic_team.team_a.sponsorship_extent": "AthleticTeam_SponsorshipExtentDescription_A",
            "athletic_team.team_b.sport_description": "AthleticTeam_SportDescription_B",
            "athletic_team.team_b.contact_sport": "AthleticTeam_ContactSportCode_B",
            "athletic_team.team_b.age_group_twelve_and_under": "AthleticTeam_AgeGroup_TwelveAndUnderIndicator_B",
            "athletic_team.team_b.age_group_thirteen_through_eighteen": "AthleticTeam_AgeGroup_ThirteenThroughEighteenIndicator_B",
            "athletic_team.team_b.age_group_over_eighteen": "AthleticTeam_AgeGroup_OverEighteenIndicator_B",
            "athletic_team.team_b.sponsorship_extent": "AthleticTeam_SponsorshipExtentDescription_B",
            "swimming_pool.approved_fence": "SwimmingPool_ApprovedFenceIndicator_A",
            "swimming_pool.limited_access": "SwimmingPool_LimitedAccessIndicator_A",
            "swimming_pool.diving_board": "SwimmingPool_DivingBoardIndicator_A",
            "swimming_pool.slide": "SwimmingPool_SlideIndicator_A",
            "swimming_pool.above_ground": "SwimmingPool_AboveGroundIndicator_A",
            "swimming_pool.in_ground": "SwimmingPool_InGroundIndicator_A",
            "swimming_pool.life_guard": "SwimmingPool_LifeGuardIndicator_A",
            "building_occupancy.apartment_count": "BuildingOccupancy_ApartmentCount_A",
            "building_occupancy.apartment_area": "BuildingOccupancy_ApartmentArea_A",
            "additional_interests[0].name": "AdditionalInterest_FullName_A",
            "additional_interests[0].interest_type": "AdditionalInterest_Interest_MortgageeIndicator_A",
            "additional_interests[0].certificate_required": "AdditionalInterest_CertificateRequiredIndicator_A",
            "additional_interests[0].mailing_address.line_one": "AdditionalInterest_MailingAddress_LineOne_A",
            "additional_interests[0].mailing_address.city": "AdditionalInterest_MailingAddress_CityName_A",
            "additional_interests[0].mailing_address.state": "AdditionalInterest_MailingAddress_StateOrProvinceCode_A",
            "additional_interests[0].mailing_address.postal_code": "AdditionalInterest_MailingAddress_PostalCode_A",
            "additional_interests[0].mailing_address.country": "AdditionalInterest_MailingAddress_CountryCode_A",
            "additional_interests[0].account_number": "AdditionalInterest_AccountNumberIdentifier_A",
            "commercial_inland_marine_property.small_tools": "CommercialInlandMarineProperty_PropertySubClass_SmallToolsIndicator_A",
            "commercial_inland_marine_property.large_equipment": "CommercialInlandMarineProperty_PropertySubClass_LargeEquipmentIndicator_A",
            "commercial_inland_marine_property.instruction_given_code": "PropertyItem_ItemDetail_InstructionGivenCode_A"
}

def get_field_mapping(form_type: str) -> Dict[str, str]:
    """Return the mapping for ACORD 126; raises on anything else."""
    if form_type != "126":
        raise ValueError("Unsupported ACORD form type: {form_type}. Only '126' is supported in this build.")
    return ACORD_126_FIELD_MAP.copy()

def get_supported_forms() -> list:
    """List of supported forms in this build."""
    return ["126"]
