[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
# Wrap in sh -c to expand $PORT
startCommand = "/bin/sh -c 'gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --log-level info main:app'"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONUNBUFFERED = "1"